import type { Lang } from "./i18n";

/** Interface copy shared by server and client components. Page content
 *  (services, products, about text…) lives in the content files instead. */
const ka = {
  meta: {
    siteName: "სერვის პრო",
    title: "სერვის პრო — საინჟინრო-სამშენებლო კომპანია",
    description:
      "შპს „სერვის პრო“ — 1996 წლიდან: HVAC (გათბობა, ვენტილაცია, ჰაერის კონდიცირება), წყალ-კანალიზაცია, თბო-, ჰიდრო- და ხმის იზოლაცია, სენდვიჩ პანელები, შეკიდული ჭერები, საწარმოო და სამედიცინო ობიექტების ტექნოლოგიური დაგეგმარება.",
    ogDescription:
      "საინჟინრო გუნდი 1996 წლიდან: HVAC, წყალ-კანალიზაცია, იზოლაცია, პანელები, ტექნოლოგიური დაგეგმარება.",
    locale: "ka_GE",
    about:
      "შპს „სერვის პრო“ — საინჟინრო გუნდი 1996 წლიდან. თბოტექნიკა, ვენტილაცია, კონდიცირება, წყალ-კანალიზაცია, იზოლაცია, პანელოვანი სისტემები და ტექნოლოგიური დაგეგმარება.",
    services:
      "HVAC, წყალმომარაგება-კანალიზაცია, ელექტროობა, თბო-, ჰიდრო- და ხმის იზოლაცია, სენდვიჩ და დეკორატიული პანელები, შეკიდული ჭერები, იატაკები, ბეტონის ბურღვა, ტექნოლოგიური დაგეგმარება.",
    products:
      "ვინილის იატაკები და LVT, სამშენებლო ქიმია, ტექსტილის ჰაერსადენები, სენდვიჩ და დეკორატიული პანელები, მაცივარ-აგრეგატები, თბოსაიზოლაციო სისტემები, HVAC აგრეგატები, შეკიდული ჭერები.",
    projects:
      "სერვის პროს შესრულებული პროექტები — სასტუმროები, კლინიკები, სკოლები, საწარმოები: გათბობა, ვენტილაცია, კონდიცირება, წყალ-კანალიზაცია, სარემონტო სამუშაოები.",
    gallery:
      "სერვის პროს შესრულებული სამუშაოები: HVAC სისტემები, ჰაერსადენები, ქვაბები, იზოლაცია, სენდვიჩ პანელები, იატაკები და შეკიდული ჭერები ობიექტებზე.",
  },
  common: {
    home: "მთავარი",
    breadcrumb: "ნავიგაცია",
    writeUs: "მოგვწერეთ",
    requestOffer: "მოითხოვეთ შეთავაზება",
    phone: "ტელეფონი",
    email: "ელ-ფოსტა",
    address: "მისამართი",
    company: "კომპანია",
    partners: "პარტნიორები",
    photo: "ფოტო",
    photos: (n: number) => `${n} ფოტო`,
    close: "დახურვა",
    prev: "წინა",
    next: "შემდეგი",
    prevPhoto: "წინა ფოტო",
    nextPhoto: "შემდეგი ფოტო",
    enlargePhoto: "ფოტოს გადიდება",
    enlarge: "გადიდება",
    photoN: (n: number) => `ფოტო ${n}`,
    photoGallery: "ფოტო გალერეა",
    more: "დეტალურად",
    view: "ნახვა",
  },
  header: {
    skip: "მთავარ კონტენტზე გადასვლა",
    brand: "სერვის პრო — მთავარი",
    nav: "მთავარი ნავიგაცია",
    language: "საიტის ენა",
    cta: "მოითხოვე კონსულტაცია",
    openMenu: "მენიუს გახსნა",
    closeMenu: "მენიუს დახურვა",
  },
  footer: { pages: "გვერდები", contact: "კონტაქტი", rights: "ყველა უფლება დაცულია" },
  hero: { stats: "კომპანიის მაჩვენებლები" },
  home: {
    whatWeDo: "რას ვაკეთებთ?",
    ourServices: "ჩვენი სერვისები",
    servicesLead: (n: number) => `${n} სერვისი — პროექტირებიდან მონტაჟამდე.`,
    allServices: (n: number) => `ყველა სერვისი — ${n}`,
    about: "ჩვენ შესახებ",
    aboutTitle: "ერთ-ერთი პირველი თბოტექნიკური გუნდი საქართველოში",
    aboutFacts: (n: number) => [
      { k: "გათბობის სისტემები", v: "18–1000 კვტ/სთ" },
      { k: "ორთქლის სადგურები", v: "სამრეწველო ტიპი" },
      { k: "კერძო სახლი და ბინა", v: "ათასობით ობიექტი" },
      { k: "სერვისები", v: `${n} მიმართულება` },
    ],
    fullStory: "სრული ისტორია",
    deckAlt: "სერვის პროს ობიექტი — დეკის ტერასა",
    clinicAlt: "სერვის პროს ობიექტი — კლინიკა",
    gallery: "გალერეა",
    galleryTitle: "შესრულებული სამუშაოები",
    allPhotos: (n: number) => `ყველა ფოტო — ${n}`,
    cooperation: "თანამშრომლობა",
    ctaTitle: (y: number) => `ჩვენი საინჟინრო გუნდი თქვენს სამსახურშია ${y} წლიდან`,
  },
  about: {
    title: "ჩვენ შესახებ",
    brand: "სერვის პრო",
    lead: (tagline: string, y: number) => `${tagline} — ${y} წლიდან.`,
    years: (n: number) => `${n} წელი`,
    history: "ისტორია",
    historyTitle: "ერთ-ერთი პირველი თბოტექნიკური გუნდი საქართველოში",
    activity: "საქმიანობა",
    deckAlt: "სერვის პროს ობიექტი — დეკის იატაკი ტერასაზე",
    lobbyAlt: "სერვის პროს ობიექტი — ლობის ინტერიერი",
    founded: "გუნდის ჩამოყალიბება",
    numbers: "რიცხვები",
    numbersTitle: (n: number) => `${n} წლიანი გამოცდილება საინჟინრო საქმიანობაში`,
  },
  services: {
    title: "სერვისები",
    whatWeDo: "რას ვაკეთებთ?",
    ourServices: "ჩვენი სერვისები",
    lead: (n: number) => `${n} სერვისი — დააჭირეთ ქარდს დეტალებისა და ფოტოების სანახავად.`,
    directions: "მიმართულებები",
    directionsTitle: "ძირითადი მიმართულებები",
    subCount: (n: number) => `+${n} ქვე-სერვისი`,
    subServices: (n: number) => `${n} ქვე-სერვისი`,
    description: "სერვისის აღწერა",
    subTitle: "ქვე-სერვისები",
    photos: "ფოტოები",
  },
  products: {
    title: "რასაც პირდაპირ ვაწოდებთ",
    eyebrow: "პროდუქტები",
    lead: "ევროპული მწარმოებლების პროდუქცია — მოწოდება მონტაჟთან და სერვისთან ერთად.",
    catalog: "კატალოგი",
    catalogTitle: "პროდუქციის უწყისი",
    catalogLead: (n: number) =>
      `${n} მიმართულება. თითოეულზე მოწოდების, მონტაჟისა და შემდგომი სერვისის შესაძლებლობით.`,
    subCategories: "ქვე-კატეგორიები",
    subCount: (n: number) => `${n} ქვე-კატეგორია`,
    pickDirection: "აირჩიეთ მიმართულება",
    subLead: (n: number) => `${n} ქვე-კატეგორია — თითოეულს საკუთარი ასორტიმენტი აქ.`,
    description: "აღწერა",
    details: "დეტალური ინფორმაცია",
    range: "ასორტიმენტი",
    models: "მოდელები და ტიპები",
    allPhotos: "ყველა ფოტო",
    rangeLead: (n: number, captioned: boolean) =>
      `${n} ${captioned ? "პოზიცია" : "ფოტო"} — დააჭირეთ გასადიდებლად.`,
    video: "ვიდეო",
    sameCategory: "ამავე კატეგორიიდან",
    backToCategory: "კატეგორიაზე დაბრუნება",
    onRequest: "+ მოთხოვნით",
    alternative: "მოგვწერეთ — შეგირჩევთ ალტერნატივას.",
  },
  cta: {
    productTitle: "გჭირდებათ ფასი კონკრეტულ პროდუქტზე?",
    productText: "მიუთითეთ პროდუქტი და რაოდენობა — მოგაწოდებთ მიმდინარე ფასს და მოწოდების ვადას.",
  },
  projects: {
    title: "პროექტები",
    lead: "კომპანიები და ორგანიზაციები, რომლებთანაც ვიმუშავეთ, და სამუშაოები, რომლებიც მათთვის შევასრულეთ.",
    eyebrow: "ჩვენი დამკვეთები",
    heading: "შესრულებული პროექტები",
    hint: "დააჭირეთ ბლოკს შესრულებული სამუშაოების სანახავად.",
    kinds: (n: number) => `${n} სახის სამუშაო`,
    project: "პროექტი",
    works: "შესრულებული სამუშაოები",
    similar: "მსგავსი პროექტი? დაგვიკავშირდით",
    ctaTitle: "გაქვთ მსგავსი პროექტი?",
    ctaText: "აღწერეთ ობიექტი და სამუშაოები — მოგიმზადებთ შეთავაზებას და ვადებს.",
    quote: (name: string) => `„${name}“`,
    fullName: (form: string, name: string) => `${form} „${name}“`,
    completed: "დასრულებული",
    ongoing: "მიმდინარე",
    ongoingProject: "მიმდინარე პროექტი",
    scope: "სამუშაოების ფარგლები",
    tabs: "პროექტების სტატუსი",
  },
  gallery: {
    title: "გალერეა",
    heading: "შესრულებული სამუშაოები",
    lead: "ფოტოები ობიექტებიდან — მონტაჟის პროცესი და დასრულებული სისტემები.",
    all: "ყველა",
    categories: "გალერეის კატეგორიები",
    morePhotos: (n: number) => `კიდევ ${n} ფოტო`,
  },
  contact: {
    title: "კონტაქტი",
    heading: "დაგვიკავშირდით",
    mapTitle: "სერვის პროს მდებარეობა რუკაზე",
    formTitle: "საკონტაქტო ფორმა",
    name: "სახელი",
    subject: "თემა",
    message: "შეტყობინება",
    sending: "იგზავნება…",
    send: "გაგზავნა",
    errRequired: "შეავსეთ სახელი, ელ-ფოსტა და შეტყობინება.",
    errEmail: "ელ-ფოსტა არასწორია.",
    errNoSmtp: (phone: string, email: string) =>
      `ფორმა ჯერ არ არის ფოსტასთან დაკავშირებული. დაგვირეკეთ ${phone} ან მოგვწერეთ ${email}.`,
    sent: "შეტყობინება გაიგზავნა. დაგიკავშირდებით უახლოეს დროს.",
    errSend: (phone: string) => `გაგზავნა ვერ მოხერხდა. დაგვირეკეთ ${phone}.`,
  },
  notFound: {
    error: "შეცდომა 404",
    title: "გვერდი ვერ მოიძებნა",
    lead: "მისამართი შეიცვალა ან აღარ არსებობს. აქედან განაგრძეთ:",
  },
};

export type Dict = typeof ka;

const en: Dict = {
  meta: {
    siteName: "Service Pro",
    title: "Service Pro — Engineering & Construction Company",
    description:
      "Service Pro LLC, since 1996: HVAC (heating, ventilation, air conditioning), water supply and sewerage, thermal, waterproofing and acoustic insulation, sandwich panels, suspended ceilings, and process planning for industrial and medical facilities.",
    ogDescription:
      "An engineering team since 1996: HVAC, water and sewerage, insulation, panels, process planning.",
    locale: "en_US",
    about:
      "Service Pro LLC — an engineering team since 1996. Heating, ventilation, air conditioning, water and sewerage, insulation, panel systems and process planning.",
    services:
      "HVAC, water supply and sewerage, electrical works, thermal, waterproofing and acoustic insulation, sandwich and decorative panels, suspended ceilings, flooring, concrete drilling, process planning.",
    products:
      "Vinyl flooring and LVT, construction chemicals, textile air ducts, sandwich and decorative panels, refrigeration units, thermal insulation systems, HVAC units, suspended ceilings.",
    projects:
      "Projects completed by Service Pro — hotels, clinics, schools and factories: heating, ventilation, air conditioning, water and sewerage, renovation works.",
    gallery:
      "Work completed by Service Pro: HVAC systems, ductwork, boilers, insulation, sandwich panels, flooring and suspended ceilings on site.",
  },
  common: {
    home: "Home",
    breadcrumb: "Breadcrumb",
    writeUs: "Write to us",
    requestOffer: "Request a quote",
    phone: "Phone",
    email: "Email",
    address: "Address",
    company: "Company",
    partners: "Partners",
    photo: "Photo",
    photos: (n) => `${n} ${n === 1 ? "photo" : "photos"}`,
    close: "Close",
    prev: "Previous",
    next: "Next",
    prevPhoto: "Previous photo",
    nextPhoto: "Next photo",
    enlargePhoto: "Enlarge photo",
    enlarge: "Enlarge",
    photoN: (n) => `Photo ${n}`,
    photoGallery: "Photo gallery",
    more: "Learn more",
    view: "View",
  },
  header: {
    skip: "Skip to main content",
    brand: "Service Pro — home",
    nav: "Main navigation",
    language: "Site language",
    cta: "Request a consultation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  footer: { pages: "Pages", contact: "Contact", rights: "All rights reserved" },
  hero: { stats: "Company figures" },
  home: {
    whatWeDo: "What we do",
    ourServices: "Our services",
    servicesLead: (n) => `${n} services — from design to installation.`,
    allServices: (n) => `All services — ${n}`,
    about: "About us",
    aboutTitle: "One of the first heating engineering teams in Georgia",
    aboutFacts: (n) => [
      { k: "Heating systems", v: "18–1000 kW" },
      { k: "Steam stations", v: "Industrial grade" },
      { k: "Private houses and flats", v: "Thousands of sites" },
      { k: "Services", v: `${n} lines of work` },
    ],
    fullStory: "Our full story",
    deckAlt: "Service Pro project — deck terrace",
    clinicAlt: "Service Pro project — clinic",
    gallery: "Gallery",
    galleryTitle: "Completed work",
    allPhotos: (n) => `All photos — ${n}`,
    cooperation: "Work with us",
    ctaTitle: (y) => `Our engineering team has been at your service since ${y}`,
  },
  about: {
    title: "About us",
    brand: "Service Pro",
    lead: (tagline, y) => `${tagline} — since ${y}.`,
    years: (n) => `${n} years`,
    history: "History",
    historyTitle: "One of the first heating engineering teams in Georgia",
    activity: "What we do",
    deckAlt: "Service Pro project — decking on a terrace",
    lobbyAlt: "Service Pro project — lobby interior",
    founded: "Team founded",
    numbers: "In numbers",
    numbersTitle: (n) => `${n} years of experience in engineering`,
  },
  services: {
    title: "Services",
    whatWeDo: "What we do",
    ourServices: "Our services",
    lead: (n) => `${n} services — open a card for details and photos.`,
    directions: "Directions",
    directionsTitle: "Main areas of work",
    subCount: (n) => `+${n} sub-services`,
    subServices: (n) => `${n} sub-services`,
    description: "About this service",
    subTitle: "Sub-services",
    photos: "Photos",
  },
  products: {
    title: "What we supply directly",
    eyebrow: "Products",
    lead: "Products from European manufacturers — supplied together with installation and service.",
    catalog: "Catalogue",
    catalogTitle: "Product range",
    catalogLead: (n) => `${n} product lines, each available with supply, installation and after-sales service.`,
    subCategories: "Subcategories",
    subCount: (n) => `${n} subcategories`,
    pickDirection: "Choose a category",
    subLead: (n) => `${n} subcategories — each with its own range.`,
    description: "Description",
    details: "Detailed information",
    range: "Range",
    models: "Models and types",
    allPhotos: "All photos",
    rangeLead: (n, captioned) =>
      `${n} ${captioned ? (n === 1 ? "item" : "items") : n === 1 ? "photo" : "photos"} — click to enlarge.`,
    video: "Video",
    sameCategory: "From the same category",
    backToCategory: "Back to category",
    onRequest: "+ On request",
    alternative: "Write to us and we will find an alternative.",
  },
  cta: {
    productTitle: "Need a price for a specific product?",
    productText: "Tell us the product and quantity, and we will send you the current price and delivery time.",
  },
  projects: {
    title: "Projects",
    lead: "Companies and organisations we have worked with, and the work we carried out for them.",
    eyebrow: "Our clients",
    heading: "Completed projects",
    hint: "Click a block to see the work carried out.",
    kinds: (n) => `${n} types of work`,
    project: "Project",
    works: "Work carried out",
    similar: "Similar project? Contact us",
    ctaTitle: "Have a similar project?",
    ctaText: "Describe the site and the work, and we will prepare a quote and timeline.",
    quote: (name) => name,
    fullName: (form, name) => `${name} ${form}`,
    completed: "Completed",
    ongoing: "Ongoing",
    ongoingProject: "Ongoing project",
    scope: "Scope of work",
    tabs: "Project status",
  },
  gallery: {
    title: "Gallery",
    heading: "Completed work",
    lead: "Photos from our sites — installation in progress and finished systems.",
    all: "All",
    categories: "Gallery categories",
    morePhotos: (n) => `${n} more photos`,
  },
  contact: {
    title: "Contact",
    heading: "Get in touch",
    mapTitle: "Service Pro location on the map",
    formTitle: "Contact form",
    name: "Name",
    subject: "Subject",
    message: "Message",
    sending: "Sending…",
    send: "Send",
    errRequired: "Please fill in your name, email and message.",
    errEmail: "That email address is not valid.",
    errNoSmtp: (phone, email) =>
      `The form is not connected to email yet. Please call us on ${phone} or write to ${email}.`,
    sent: "Your message has been sent. We will get back to you shortly.",
    errSend: (phone) => `Sending failed. Please call us on ${phone}.`,
  },
  notFound: {
    error: "Error 404",
    title: "Page not found",
    lead: "The address has changed or no longer exists. Continue from here:",
  },
};

export const dicts: Record<Lang, Dict> = { ka, en };
