/**
 * Product catalogue. Names, copy and photos are carried over from the
 * company's previous site (service-pro.ge/products and its inner pages).
 * Gallery files live in /public/img/products/<slug>/.
 *
 * Generated once from the old site, then edited by hand — keep it that way.
 */

import { makeCatalog, type Item } from "./catalog";

export type { Shot } from "./catalog";
export type Product = Item;

export const products: Product[] = [
  {
    slug: "vinyl-floors",
    t: "ვინილის იატაკები",
    d: "ვინილის იატაკის და კედლის საფარები, მათ შორის LVT (ვინილის დეკორატიული ფილები).",
    img: "/img/products/vinyl-floors.jpg",
    gallery: [
      { src: "/img/products/vinyl-floors/01.jpg" },
      { src: "/img/products/vinyl-floors/02.jpg" },
      { src: "/img/products/vinyl-floors/03.jpg" },
      { src: "/img/products/vinyl-floors/04.jpg" },
      { src: "/img/products/vinyl-floors/05.jpg" },
      { src: "/img/products/vinyl-floors/06.jpg" },
      { src: "/img/products/vinyl-floors/07.jpg" },
      { src: "/img/products/vinyl-floors/08.jpg" },
      { src: "/img/products/vinyl-floors/09.jpg" },
      { src: "/img/products/vinyl-floors/10.jpg" },
      { src: "/img/products/vinyl-floors/11.jpg" },
      { src: "/img/products/vinyl-floors/12.jpg" },
      { src: "/img/products/vinyl-floors/13.jpg" },
    ],
  },
  {
    slug: "construction-chemicals",
    t: "სამშენებლო ქიმია",
    d: "სამშენებლო ქიმია იატაკის საფუძვლის მოსამზადებლად და ვინილის საფარის დასაწებებლად.",
    img: "/img/products/construction-chemicals.jpg",
    gallery: [],
  },
  {
    slug: "textile-ducts",
    t: "ტექსტილის ჰაერსადენები",
    d: "ტექსტილის ჰაერსადენები და მათი საკიდი სისტემები.",
    img: "/img/products/textile-ducts.jpg",
    gallery: [
      { src: "/img/products/textile-ducts/01.png" },
      { src: "/img/products/textile-ducts/02.jpg" },
      { src: "/img/products/textile-ducts/03.png" },
      { src: "/img/products/textile-ducts/04.jpg" },
      { src: "/img/products/textile-ducts/05.png" },
      { src: "/img/products/textile-ducts/06.jpg" },
      { src: "/img/products/textile-ducts/07.png" },
      { src: "/img/products/textile-ducts/08.png" },
      { src: "/img/products/textile-ducts/09.png" },
      { src: "/img/products/textile-ducts/10.jpg" },
      { src: "/img/products/textile-ducts/11.jpg" },
      { src: "/img/products/textile-ducts/12.jpg" },
      { src: "/img/products/textile-ducts/13.jpg" },
      { src: "/img/products/textile-ducts/14.jpg" },
    ],
  },
  {
    slug: "cold-storage-systems",
    t: "სამაცივრე და სასაწყობო სისტემები",
    d: "ავტომატური და მექანიკური კარებები; სამაცივრე და სასაწყობო მოწყობილობები; საქონლის დატვირთვა-დაცლის პანდუსის სისტემები.",
    img: "/img/products/cold-storage-systems.jpg",
    children: ["cold-storage-doors", "loading-ramps"],
    fit: "contain",
    gallery: [
      { src: "/img/products/cold-storage-systems/01.jpg", caption: "ასაკეცი ტექსტილის კარი" },
      { src: "/img/products/cold-storage-systems/02.jpg", caption: "დამტვირთველ-დამცლელი კამერები" },
      { src: "/img/products/cold-storage-systems/03.png", caption: "ინდუსტრიული კარი" },
      { src: "/img/products/cold-storage-systems/04.jpg", caption: "სტანდარტული როლეტის ტიპის სწრაფი კარი" },
    ],
  },
  {
    slug: "soft-floors",
    t: "რბილი იატაკები",
    d: "რბილი იატაკების სრული სპექტრი.",
    img: "/img/products/soft-floors.webp",
    gallery: [
      { src: "/img/products/soft-floors/01.webp" },
      { src: "/img/products/soft-floors/02.jpg" },
      { src: "/img/products/soft-floors/03.jpg" },
      { src: "/img/products/soft-floors/04.jpg" },
      { src: "/img/products/soft-floors/05.webp" },
      { src: "/img/products/soft-floors/06.jpg" },
      { src: "/img/products/soft-floors/07.jpg" },
      { src: "/img/products/soft-floors/08.jpg" },
      { src: "/img/products/soft-floors/09.jpg" },
      { src: "/img/products/soft-floors/10.jpg" },
    ],
  },
  {
    slug: "sandwich-panels",
    t: "სენდვიჩ პანელები",
    d: "სენდვიჩ პანელები — პოლიურეთანის PUR, პოლიიზოციანურატის PIR, ქვაბამბის და სხვა.",
    img: "/img/products/sandwich-panels.jpg",
    gallery: [
      { src: "/img/products/sandwich-panels/01.jpg", caption: "ქვაბამბის სახურავის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/02.jpg", caption: "ქვაბამბის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/03.jpg", caption: "ქვაბამბის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/04.webp", caption: "ქვაბამბის სახურავის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/05.jpg", caption: "პოლიურეთანის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/06.jpg", caption: "პოლიურეთანის სახურავის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/07.jpg", caption: "პოლიურეთანის სასახურავე სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/08.jpg", caption: "პოლიურეთანის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/09.webp", caption: "კომბინირებული სენდვიჩ-პანელი" },
    ],
  },
  {
    slug: "decorative-panels",
    t: "დეკორატიული პანელები",
    d: "დეკორატიული პანელები ინტერიერისა და ფასადებისათვის (Neteren).",
    img: "/img/products/decorative-panels.jpg",
    intro: [
      { p: "ეს არის კედლის და ჭერის მოსაპირკეთებელი მზა პანელები – გარე და შიდა ფასადებისათვის. ისინი პოლიესტერის მასალით, მინაბოჭკოთი, ბუნებრივი ხისა და ქვის ფხვნილებითა და სპეციალური ქიმიური ნივთიერებების სინთეზით მზადდება. ეკოლოგიურად სუფთაა. ხელით შეხებისასაც ნამდვილი, ნატურალური მასალის შეგრძნებას იძლევა. ამ პანელების დამამზადებლები ევროპული კომპანიები არიან, ხოლო საქართველოში ჩვენ შემოგვაქვს და ვამონტაჟებთ." },
      { p: "ნუღარ დაკარგავთ დროს სხვა გადაწყვეტილებების ძებნაში, დაგვიკავშირდით და მიიღეთ ჩვენგან ნებისმიერი თქვენთვის სასურველი ზედაპირისა და ტექსტურის მქონე მზა პანელები ადგილზე მიწოდებითა და უსწრაფესი მონტაჟით." },
    ],
    gallery: [
      { src: "/img/products/decorative-panels/01.jpg" },
      { src: "/img/products/decorative-panels/02.jpg" },
      { src: "/img/products/decorative-panels/03.jpg" },
      { src: "/img/products/decorative-panels/04.jpg" },
      { src: "/img/products/decorative-panels/05.jpg" },
      { src: "/img/products/decorative-panels/06.jpg" },
      { src: "/img/products/decorative-panels/07.jpg" },
      { src: "/img/products/decorative-panels/08.jpg" },
      { src: "/img/products/decorative-panels/09.jpg" },
      { src: "/img/products/decorative-panels/10.jpg" },
      { src: "/img/products/decorative-panels/11.jpg" },
      { src: "/img/products/decorative-panels/12.jpg" },
      { src: "/img/products/decorative-panels/13.jpg" },
      { src: "/img/products/decorative-panels/14.jpg" },
      { src: "/img/products/decorative-panels/15.jpg" },
      { src: "/img/products/decorative-panels/16.jpg" },
      { src: "/img/products/decorative-panels/17.jpg" },
      { src: "/img/products/decorative-panels/18.jpg" },
      { src: "/img/products/decorative-panels/19.jpg" },
      { src: "/img/products/decorative-panels/20.jpg" },
      { src: "/img/products/decorative-panels/21.jpg" },
      { src: "/img/products/decorative-panels/22.jpg" },
      { src: "/img/products/decorative-panels/23.jpg" },
      { src: "/img/products/decorative-panels/24.jpg" },
      { src: "/img/products/decorative-panels/25.jpg" },
      { src: "/img/products/decorative-panels/26.jpg" },
      { src: "/img/products/decorative-panels/27.jpg" },
      { src: "/img/products/decorative-panels/28.jpg" },
      { src: "/img/products/decorative-panels/29.jpg" },
      { src: "/img/products/decorative-panels/30.jpg" },
      { src: "/img/products/decorative-panels/31.jpg" },
      { src: "/img/products/decorative-panels/32.jpg" },
      { src: "/img/products/decorative-panels/33.jpg" },
      { src: "/img/products/decorative-panels/34.jpg" },
      { src: "/img/products/decorative-panels/35.jpg" },
      { src: "/img/products/decorative-panels/36.jpg" },
      { src: "/img/products/decorative-panels/37.jpg" },
      { src: "/img/products/decorative-panels/38.jpg" },
      { src: "/img/products/decorative-panels/39.jpg" },
      { src: "/img/products/decorative-panels/40.jpg" },
      { src: "/img/products/decorative-panels/41.jpg" },
      { src: "/img/products/decorative-panels/42.jpg" },
      { src: "/img/products/decorative-panels/43.jpg" },
      { src: "/img/products/decorative-panels/44.jpg" },
      { src: "/img/products/decorative-panels/45.jpg" },
      { src: "/img/products/decorative-panels/46.jpg" },
      { src: "/img/products/decorative-panels/47.jpg" },
      { src: "/img/products/decorative-panels/48.jpg" },
      { src: "/img/products/decorative-panels/49.jpg" },
      { src: "/img/products/decorative-panels/50.jpg" },
    ],
  },
  {
    slug: "chiller-units",
    t: "მაცივარ-აგრეგატები",
    d: "მაცივარ აგრეგატები, სამაცივრე სისტემები.",
    img: "/img/products/chiller-units.jpg",
    gallery: [],
  },
  {
    slug: "thermal-insulation",
    t: "თბოიზოლაცია",
    d: "შენობის სრული თბოიზოლირება (სახურავი, კედლები, იატაკი) პოლიურეთანის (PIR) ქაფით ან ფილებით; ორთქლის, ცხელი და გაცივებული წყლის მილსადენების, თბომცვლელებისა და საწარმოო-ტექნოლოგიური მოწყობილობების თბოიზოლაცია პრეფაბრიკული მილებითა და მეტალის გარსაცმებით. ჩამკეტ-მარეგულირებელი არმატურის თბოიზოლირება სწრაფად მოხსნადი „ჯეკეტებით“.",
    img: "/img/products/thermal-insulation.jpg",
    children: ["insulation-jackets", "pir-spray-foam", "pir-boards", "prefabricated-pipes"],
    gallery: [
      { src: "/img/products/thermal-insulation/01.jpg" },
      { src: "/img/products/thermal-insulation/02.jpg" },
      { src: "/img/products/thermal-insulation/03.jpg" },
      { src: "/img/products/thermal-insulation/04.jpg" },
      { src: "/img/products/thermal-insulation/05.webp" },
    ],
  },
  {
    slug: "decorative-glass",
    t: "დეკორატიული მინა (დეკომინა)",
    d: "დეკორატიული, გოფრირებული მინა (დეკომინა).",
    img: "/img/products/decorative-glass.jpg",
    video: "/img/products/decorative-glass/19.mp4",
    gallery: [
      { src: "/img/products/decorative-glass/01.jpg" },
      { src: "/img/products/decorative-glass/02.jpg" },
      { src: "/img/products/decorative-glass/03.jpg" },
      { src: "/img/products/decorative-glass/04.jpg" },
      { src: "/img/products/decorative-glass/05.jpg" },
      { src: "/img/products/decorative-glass/06.jpg" },
      { src: "/img/products/decorative-glass/07.jpg" },
      { src: "/img/products/decorative-glass/08.jpg" },
      { src: "/img/products/decorative-glass/09.jpg" },
      { src: "/img/products/decorative-glass/10.jpg" },
      { src: "/img/products/decorative-glass/11.jpg" },
      { src: "/img/products/decorative-glass/12.jpg" },
      { src: "/img/products/decorative-glass/13.jpg" },
      { src: "/img/products/decorative-glass/14.jpg" },
      { src: "/img/products/decorative-glass/15.jpg" },
      { src: "/img/products/decorative-glass/16.jpg" },
      { src: "/img/products/decorative-glass/17.jpg" },
      { src: "/img/products/decorative-glass/18.jpg" },
    ],
  },
  {
    slug: "steam-units",
    t: "თბოუზრუნველყოფის აგრეგატები",
    d: "ორთქლის ქვაბები, ორთქლის სადგურის მოწყობილობები, წყლის გამწმენდი სისტემები.",
    img: "/img/products/steam-units.jpg",
    gallery: [],
  },
  {
    slug: "water-treatment",
    t: "წყლის გამწმენდი სისტემები",
    d: "წყლის ფილტრაციის, დარბილების და წმენდის სისტემები.",
    img: "/img/products/water-treatment/cover.png",
    gallery: [],
  },
  {
    slug: "automation",
    t: "ავტომატიზაცია და ავტომატური კონტროლი",
    d: "HVAC, წყალმომარაგების და ორთქლის სისტემების ავტომატური მართვა და კონტროლი.",
    // Placeholder photo until the client sends automation shots.
    img: "/img/products/hvac/05.jpg",
    gallery: [],
  },
  {
    slug: "deck-floors",
    t: "დეკის იატაკები",
    d: "დეკის იატაკები და სამონტაჟო ელემენტების სრული სპექტრი.",
    img: "/img/products/deck-floors.jpg",
    gallery: [
      { src: "/img/products/deck-floors/01.jpg" },
      { src: "/img/products/deck-floors/02.jpg" },
      { src: "/img/products/deck-floors/03.jpg" },
      { src: "/img/products/deck-floors/04.jpg" },
      { src: "/img/products/deck-floors/05.webp" },
      { src: "/img/products/deck-floors/06.webp" },
      { src: "/img/products/deck-floors/07.jpg" },
      { src: "/img/products/deck-floors/08.png" },
      { src: "/img/products/deck-floors/09.jpg" },
      { src: "/img/products/deck-floors/11.jpg" },
      { src: "/img/products/deck-floors/12.jpg" },
      { src: "/img/products/deck-floors/13.jpg" },
      { src: "/img/products/deck-floors/14.jpg" },
      { src: "/img/products/deck-floors/15.jpg" },
      { src: "/img/products/deck-floors/16.jpg" },
      { src: "/img/products/deck-floors/17.jpg" },
      { src: "/img/products/deck-floors/18.jpg" },
      { src: "/img/products/deck-floors/19.jpg" },
      { src: "/img/products/deck-floors/20.jpg" },
      { src: "/img/products/deck-floors/21.jpg" },
      { src: "/img/products/deck-floors/23.jpg" },
      { src: "/img/products/deck-floors/26.jpg" },
      { src: "/img/products/deck-floors/27.jpg" },
      { src: "/img/products/deck-floors/29.jpg" },
      { src: "/img/products/deck-floors/30.jpg" },
      { src: "/img/products/deck-floors/31.jpg" },
      { src: "/img/products/deck-floors/32.png" },
      { src: "/img/products/deck-floors/33.jpg" },
    ],
  },
  {
    slug: "hvac",
    t: "HVAC — გათბობა, ვენტილაცია, ჰაერის კონდიცირება",
    d: "გათბობა, ვენტილაცია, ჰაერის კონდიცირების სისტემები, მათ შორის: ჰაერის დამუშავების აგრეგატები (AHU); რეკუპერატორები; ჰაერსადენები; ავტომატური კონტროლის მოწყობილობები.",
    img: "/img/products/hvac.jpg",
    children: ["ahu", "air-filters", "recuperators", "textile-ducts"],
    intro: [
      { p: "გათბობა, ვენტილაცია და ჰაერის კონდიცირება კომფორტის ის კომპონენტებია, რომლებსაც არ გააჩნიათ ხარისხის, მრავალფეროვნებისა და ღირებულების ზღვარი. შესაძლებელია ყველა ეს კომპონენტი წარმოდგენილი იყოს როგორც ცალკე სისტემა ან მოწყობილობა, ასევე ერთმანეთში ინტეგრირებული მაღალეფექტური, ცენტრალიზებული და ავტომატურად მართვადი სისტემა, რომელსაც კომპიუტერული პროგრამა ადამიანის ჩარევის გარეშე ამუშავებს." },
      { h: "დაზოგე ენერგია და ფული", p: "მიმდინარე ეკოლოგიური და ენერგეტიკული გამოწვევები გვაიძულებენ სულ უფრო მეტად დავხვეწოთ და განვავითაროთ სითბური ენერგიის უკუგების მეთოდები და მოწყობილობები. დედამიწაზე ენერგო რესურსების შემცირების ტენდენცია ენერგომატარებლებზე ფასების მუდმივ მატებას იწვევს. რეკუპერაციის გარეშე ფაქტიურად წარმოუდგენელი გახდა საშუალო და მსხვილი სიდიდის ობიექტების სითბოთი და სიცივით უზრუნველყოფა." },
      { h: "ყურადღება მიაქციე ჰაერს, რომელსაც სუნთქავ", p: "ჰაერის მხოლოდ გაცივება და გათბობა აღარ არის საკმარისი სრული კომფორტისა და ჯანმრთელი გარემოს შექმნისათვის. დღესდღეობით სულ უფრო ხშირად გვიწევს ჰაერის დამუშავებაზე ზრუნვა, რათა მისი ხარისხი საჭირო პარამეტრებს შევუსაბამოთ. ჰაერის დამუშავება ტემპერატურის რეგულირების გარდა მისი სისუფთავის, ტენიანობის და ნაკადების მართვასაც გულისხმობს." },
      { h: "გვენდე ჩვენ — შეიქმენი ჯანსაღი და კომფორტული გარემო", p: "საკმაოდ რთულია ინფორმაციულად უკიდურესად გადატვირთულ ეპოქაში ჯანსაღი და კომფორტული გარემოს შექმნისათვის საჭირო ყველა ელემენტის შესწავლა და მათგან ოპტიმალურის შერჩევა. ჩვენი საერთაშორისო გუნდი, რომელსაც აღნიშნულ სექტორში მუშაობის 30 წლიანი გამოცდილება აქვს, სიამოვნებით გაგიწევთ პროფესიონალურ კონსულტაციებს, მოგცემთ რეკომენდაციებს და შეიმუშავებს ოპტიმალურ კონცეფციას თქვენი საჭიროებისა და/ან ტექნიკური დავალების შესაბამისად." },
    ],
    gallery: [
      { src: "/img/products/hvac/01.jpg" },
      { src: "/img/products/hvac/02.jpg" },
      { src: "/img/products/hvac/03.jpg" },
      { src: "/img/products/hvac/04.jpg" },
      { src: "/img/products/hvac/05.jpg" },
      { src: "/img/products/hvac/06.jpg" },
      { src: "/img/products/hvac/07.jpg" },
    ],
  },
  {
    slug: "suspended-ceilings",
    t: "შეკიდული ჭერი",
    d: "ნებისმიერი ტიპის, მათ შორის Clip inn; Lay inn; Grilatto, ასევე ინდუსტრიული, თაბაშირ-მუყაოს და სხვა ტიპის პანელოვანი ჭერები.",
    img: "/img/products/suspended-ceilings.jpg",
    intro: [
      { h: "ჭერიც არის და ჭერიც", p: "ამოუწურავია ჭერის თემა თავისი მრავალფეროვნების გამო, მითუმეტეს, რომ დღევანდელ დღეს ჭერს უბრალო გადახურვისა და დეკორის ფუნქციის გარდა მრავალი სხვა, არანაკლებ მნიშვნელოვანი ფუნქცია შეემატა. თანამედროვე შენობებში ინტერიერის ეს მნიშვნელოვანი ელემენტი მთელ რიგ ტექნოლოგიებს მოიცავს, როგორებიც არის: თბო და ბგერითი იზოლაცია, ენერგიის დაზოგვა, ხმაურის ჩახშობა, განათების ეფექტის გაზრდა, ჰიგიენა და ბოლოს და ბოლოს შეკიდულ ჭერს მიღმა შეგვიძლია დავმალოთ ყველა და ნებისმიერი საინჟინრო კომუნიკაცია. ფუნქციონალური დატვირთვისა და შესახედაობის მიხედვით შესაძლებელია შეირჩეს სხვადასხვა ტიპისა და მასალის ჭერი." },
      { h: "ჭერის შესყიდვამდე დაგვიკავშირდით", p: "იმისათვის, რომ თქვენი ახალი ჭერი ზუსტად აკმაყოფილებდეს როგორც თქვენს გემოვნებას, ასევე თქვენს ტექნიკურ მოთხოვნებს – დაგვიკავშირდით და ჩვენი გუნდის პროფესიონალი სპეციალისტი დაგეხმარებათ ოპტიმალური გადაწყვეტილების მიღებაში. ჭერის ტიპის, კონსტრუქციისა და მასალის შერჩევა პირველ რიგში შენობის დანიშნულებიდან და ფუნქციიდან გამომდინარე ხდება. ჭერის ტიპიდან გამომდინარე ხდება მისი კონსტრუქციის განსაზღვრა, გაანგარიშება და მთლიანობაში ჭერის მოსაწყობად საჭირო მასალების დათვლა." },
      { p: "გთავაზობთ ხის, მეტალის, ვინილის, კომპოზიტური, თუ იმიტირებული მასალისაგან დამზადებული ჭერების ფართო ასორტიმენტს თქვენი ობიექტის დანიშნულებისა და ფუნქციის შესაბამისად. მასალებისა და სამუშაოს შეკვეთის შემთხვევაში რეკომენდაციები, კონსულტაცია და დაანგარიშება უფასოა." },
    ],
    gallery: [
      { src: "/img/products/suspended-ceilings/01.jpg" },
      { src: "/img/products/suspended-ceilings/02.jpg" },
      { src: "/img/products/suspended-ceilings/04.jpg" },
      { src: "/img/products/suspended-ceilings/05.jpg" },
      { src: "/img/products/suspended-ceilings/06.jpg" },
      { src: "/img/products/suspended-ceilings/07.jpg" },
      { src: "/img/products/suspended-ceilings/08.webp" },
      { src: "/img/products/suspended-ceilings/09.webp" },
      { src: "/img/products/suspended-ceilings/10.webp" },
      { src: "/img/products/suspended-ceilings/11.jpg" },
      { src: "/img/products/suspended-ceilings/12.webp" },
      { src: "/img/products/suspended-ceilings/13.webp" },
      { src: "/img/products/suspended-ceilings/14.webp" },
      { src: "/img/products/suspended-ceilings/15.webp" },
      { src: "/img/products/suspended-ceilings/16.webp" },
      { src: "/img/products/suspended-ceilings/17.webp" },
      { src: "/img/products/suspended-ceilings/18.jpg" },
      { src: "/img/products/suspended-ceilings/19.webp" },
      { src: "/img/products/suspended-ceilings/20.webp" },
      { src: "/img/products/suspended-ceilings/21.webp" },
      { src: "/img/products/suspended-ceilings/22.webp" },
      { src: "/img/products/suspended-ceilings/23.webp" },
      { src: "/img/products/suspended-ceilings/24.webp" },
      { src: "/img/products/suspended-ceilings/25.webp" },
      { src: "/img/products/suspended-ceilings/26.jpg" },
      { src: "/img/products/suspended-ceilings/27.jpg" },
      { src: "/img/products/suspended-ceilings/28.jpg" },
      { src: "/img/products/suspended-ceilings/29.jpg" },
      { src: "/img/products/suspended-ceilings/30.jpg" },
      { src: "/img/products/suspended-ceilings/31.jpg" },
      { src: "/img/products/suspended-ceilings/32.jpg" },
      { src: "/img/products/suspended-ceilings/33.jpg" },
      { src: "/img/products/suspended-ceilings/34.jpg" },
      { src: "/img/products/suspended-ceilings/35.jpg" },
      { src: "/img/products/suspended-ceilings/36.jpg" },
      { src: "/img/products/suspended-ceilings/37.png" },
      { src: "/img/products/suspended-ceilings/38.png" },
      { src: "/img/products/suspended-ceilings/39.webp" },
      { src: "/img/products/suspended-ceilings/40.jpg" },
      { src: "/img/products/suspended-ceilings/41.jpg" },
      { src: "/img/products/suspended-ceilings/42.jpg" },
      { src: "/img/products/suspended-ceilings/43.jpg" },
      { src: "/img/products/suspended-ceilings/44.jpg" },
      { src: "/img/products/suspended-ceilings/45.jpg" },
      { src: "/img/products/suspended-ceilings/46.jpg" },
      { src: "/img/products/suspended-ceilings/47.jpg" },
      { src: "/img/products/suspended-ceilings/48.jpg" },
      { src: "/img/products/suspended-ceilings/49.jpg" },
    ],
  },
];

export const subProducts: Product[] = [
  {
    slug: "cold-storage-doors",
    t: "ცივი საწყობის კარები",
    d: "ავტომატური და მექანიკური კარებები სამაცივრე და სასაწყობო ობიექტებისთვის — სრიალა, ანჯამებზე, ბარის ტიპის, სერვის და როლეტის ტიპის სწრაფი კარები.",
    img: "/img/products/cold-storage-doors/01.png",
    parent: "cold-storage-systems",
    fit: "contain",
    gallery: [
      { src: "/img/products/cold-storage-doors/01.png", caption: "ბარის ტიპის კარი, 2-ფრთიანი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/02.png", caption: "ბარის ტიპის კარი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/03.jpg", caption: "თბოიზოლირებული როლეტის ტიპის სწრაფი კარი" },
      { src: "/img/products/cold-storage-doors/04.png", caption: "კარი 1-ფრთიანი, ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/05.jpg", caption: "კარი 2-ფრთიანი, ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/06.png", caption: "სერვის კარი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/07.png", caption: "სერვის კარი" },
      { src: "/img/products/cold-storage-doors/08.png", caption: "სრიალა კარი, ავტომატური, ჰორიზონტალური" },
      { src: "/img/products/cold-storage-doors/09.png", caption: "სრიალა კარი, ვერტიკალური" },
      { src: "/img/products/cold-storage-doors/10.jpg", caption: "სრიალა კარი, ჰერმეტული, წნევის კონტროლით" },
      { src: "/img/products/cold-storage-doors/11.png", caption: "სრიალა კარი, ჰორიზონტალური" },
      { src: "/img/products/cold-storage-doors/12.png", caption: "სრიალა კარი ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/13.png", caption: "სრიალა კარი მონორელსზე" },
    ],
  },
  {
    slug: "loading-ramps",
    t: "პანდუსის სისტემები",
    d: "საქონლის დატვირთვა-დაცლის პანდუსის სისტემები — ჰიდრავლიკური და პნევმატური რამპები, კარის ღიობის შემამჭიდროვებელი სისტემები.",
    img: "/img/products/loading-ramps/01.jpg",
    parent: "cold-storage-systems",
    gallery: [
      { src: "/img/products/loading-ramps/01.jpg", caption: "პნევმატური და ჰიდრავლიკური პანდუსის სისტემები" },
      { src: "/img/products/loading-ramps/02.jpg", caption: "გასაბერი კარის ღიობის შემამჭიდროვებელი სისტემა" },
      { src: "/img/products/loading-ramps/03.jpg", caption: "კარის ღიობის შემამჭიდროვებელი ბალიშის სისტემა" },
      { src: "/img/products/loading-ramps/04.jpg", caption: "პანდუსის ავტომატური სისტემები" },
      { src: "/img/products/loading-ramps/05.png", caption: "ჰიდრავლიკური რამპის სისტემები" },
    ],
  },
  {
    slug: "insulation-jackets",
    t: "თბოსაიზოლაციო ჯეკეტები",
    d: "ჩამკეტ-მარეგულირებელი არმატურის, თბომცვლელებისა და ტექნოლოგიური მოწყობილობების თბოიზოლირება სწრაფად მოხსნადი „ჯეკეტებით“.",
    img: "/img/products/insulation-jackets/01.jpg",
    parent: "thermal-insulation",
    gallery: [
      { src: "/img/products/insulation-jackets/01.jpg" },
      { src: "/img/products/insulation-jackets/02.jpg" },
      { src: "/img/products/insulation-jackets/03.jpg" },
      { src: "/img/products/insulation-jackets/04.jpg" },
      { src: "/img/products/insulation-jackets/05.jpg" },
      { src: "/img/products/insulation-jackets/06.jpg" },
      { src: "/img/products/insulation-jackets/07.jpg" },
      { src: "/img/products/insulation-jackets/08.jpg" },
      { src: "/img/products/insulation-jackets/09.jpg" },
      { src: "/img/products/insulation-jackets/10.jpg" },
    ],
  },
  {
    slug: "pir-spray-foam",
    t: "PIR და PUR ქაფით დაფარვა",
    d: "პოლიიზოციანურატის (PIR) და პოლიურეთანის (PUR) ქაფით დაფარვა — შენობის სრული თბოიზოლირება: სახურავი, კედლები, იატაკი.",
    img: "/img/products/pir-spray-foam/01.jpg",
    parent: "thermal-insulation",
    gallery: [
      { src: "/img/products/pir-spray-foam/01.jpg" },
      { src: "/img/products/pir-spray-foam/02.jpg" },
      { src: "/img/products/pir-spray-foam/03.jpg" },
      { src: "/img/products/pir-spray-foam/04.jpg" },
      { src: "/img/products/pir-spray-foam/05.jpg" },
      { src: "/img/products/pir-spray-foam/06.jpg" },
    ],
  },
  {
    slug: "pir-boards",
    t: "PIR და PUR თბოსაიზოლაციო ფილები",
    d: "პოლიიზოციანურატის (PIR) და პოლიურეთანის (PUR) თბოსაიზოლაციო ფილები.",
    img: "/img/products/pir-boards/01.jpg",
    parent: "thermal-insulation",
    gallery: [
      { src: "/img/products/pir-boards/01.jpg" },
      { src: "/img/products/pir-boards/02.jpg" },
      { src: "/img/products/pir-boards/03.jpg" },
      { src: "/img/products/pir-boards/04.jpg" },
    ],
  },
  {
    slug: "prefabricated-pipes",
    t: "პრეფაბრიკული თბოსაიზოლაციო მილები",
    d: "პრეფაბრიკული თბოსაიზოლაციო მილები ქვაბამბის, მინაბამბის ან პოლიურეთანის (PUR და PIR) — ორთქლის, ცხელი და გაცივებული წყლის მილსადენებისთვის, მეტალის გარსაცმებით.",
    img: "/img/products/prefabricated-pipes/01.webp",
    parent: "thermal-insulation",
    fit: "contain",
    gallery: [
      { src: "/img/products/prefabricated-pipes/01.webp" },
      { src: "/img/products/prefabricated-pipes/02.png" },
      { src: "/img/products/prefabricated-pipes/03.png" },
      { src: "/img/products/prefabricated-pipes/04.jpg" },
      { src: "/img/products/prefabricated-pipes/05.png" },
      { src: "/img/products/prefabricated-pipes/06.png" },
      { src: "/img/products/prefabricated-pipes/07.png" },
      { src: "/img/products/prefabricated-pipes/08.png" },
      { src: "/img/products/prefabricated-pipes/09.png" },
      { src: "/img/products/prefabricated-pipes/10.png" },
      { src: "/img/products/prefabricated-pipes/11.png" },
      { src: "/img/products/prefabricated-pipes/12.png" },
      { src: "/img/products/prefabricated-pipes/13.png" },
      { src: "/img/products/prefabricated-pipes/14.png" },
      { src: "/img/products/prefabricated-pipes/15.png" },
      { src: "/img/products/prefabricated-pipes/16.png" },
      { src: "/img/products/prefabricated-pipes/17.png" },
      { src: "/img/products/prefabricated-pipes/18.png" },
      { src: "/img/products/prefabricated-pipes/19.png" },
      { src: "/img/products/prefabricated-pipes/20.png" },
      { src: "/img/products/prefabricated-pipes/21.png" },
      { src: "/img/products/prefabricated-pipes/22.png" },
      { src: "/img/products/prefabricated-pipes/23.png" },
      { src: "/img/products/prefabricated-pipes/24.png" },
      { src: "/img/products/prefabricated-pipes/25.png" },
      { src: "/img/products/prefabricated-pipes/26.png" },
    ],
  },
  {
    slug: "ahu",
    t: "AHU — ჰაერის დამუშავების აგრეგატები",
    d: "ცენტრალური კონდიციონერები — ჰაერის დამუშავების აგრეგატები: ჰაერის გათბობა, გაცივება, ფილტრაცია, ტენიანობისა და ნაკადების მართვა.",
    img: "/img/products/ahu/01.jpg",
    parent: "hvac",
    gallery: [
      { src: "/img/products/ahu/01.jpg" },
      { src: "/img/products/ahu/02.jpg" },
    ],
  },
  {
    slug: "air-filters",
    t: "ჰაერის ფილტრები",
    d: "ჰაერის ფილტრები HVAC სისტემებისთვის — ჰაერის სისუფთავე და ჯანსაღი გარემო შენობის შიგნით.",
    img: "/img/products/air-filters/01.png",
    parent: "hvac",
    gallery: [
      { src: "/img/products/air-filters/01.png" },
      { src: "/img/products/air-filters/02.jpg" },
      { src: "/img/products/air-filters/03.jpg" },
      { src: "/img/products/air-filters/04.jpg" },
      { src: "/img/products/air-filters/05.jpg" },
      { src: "/img/products/air-filters/06.jpg" },
    ],
  },
  {
    slug: "recuperators",
    t: "რეკუპერატორები",
    d: "რეკუპერატორები — სითბური ენერგიის უკუგება ვენტილაციის სისტემებში, ენერგიისა და ხარჯების დაზოგვა.",
    img: "/img/products/recuperators/01.jpg",
    parent: "hvac",
    gallery: [
      { src: "/img/products/recuperators/01.jpg" },
      { src: "/img/products/recuperators/02.webp" },
      { src: "/img/products/recuperators/03.png" },
      { src: "/img/products/recuperators/04.png" },
      { src: "/img/products/recuperators/05.png" },
      { src: "/img/products/recuperators/06.jpg" },
      { src: "/img/products/recuperators/07.jpg" },
    ],
  },
];

export const productCatalog = makeCatalog({
  base: "/products",
  label: "პროდუქტები",
  noun: "პროდუქტი",
  features: { label: "", items: ["მოწოდება", "მონტაჟი", "სერვისი"] },
  copy: {
    others: "სხვა პროდუქტები",
    all: "ყველა პროდუქტი",
    order: "ფასი და მოწოდების ვადა",
    cta: "გჭირდებათ ფასი კონკრეტულ პროდუქტზე?",
    missing: "არ იპოვეთ საჭირო პროდუქტი?",
  },
  top: products,
  sub: subProducts,
});

export const findProduct = productCatalog.find;
export const productHref = productCatalog.href;
export const childrenOf = productCatalog.childrenOf;
