/**
 * Services catalogue. Names, copy and photos are carried over from the
 * company's previous site (service-pro.ge/service and its inner pages).
 * Gallery files live in /public/img/services/<slug>/, or reuse the matching
 * product photo when the old site showed the same picture in both places.
 */

import { makeCatalog, type Item } from "./catalog";

export const services: Item[] = [
  {
    slug: "vinyl-flooring",
    t: "ნებისმიერი ტიპის ვინილის საფარის მოწყობა",
    d: "იატაკის ტიპის, კედლის ტიპის, PVC კედლის პანელების და დეკორატიული PVC ფილების (LVT). ასევე ამ საფარებისთვის შესაბამისი საფუძვლის მომზადება.",
    img: "/img/products/vinyl-floors/02.jpg",
    gallery: [
      { src: "/img/products/vinyl-floors/02.jpg" },
      { src: "/img/products/vinyl-floors/03.jpg" },
      { src: "/img/products/vinyl-floors/04.jpg" },
      { src: "/img/products/vinyl-floors/05.jpg" },
      { src: "/img/products/vinyl-floors/06.jpg" },
      { src: "/img/products/vinyl-floors/07.jpg" },
      { src: "/img/products/vinyl-floors/08.jpg" },
      { src: "/img/products/vinyl-floors/09.jpg" },
      { src: "/img/products/vinyl-floors/10.jpg" },
      { src: "/img/products/vinyl-floors/11.jpg" },
      { src: "/img/products/vinyl-floors/12.jpg" },
      { src: "/img/products/vinyl-floors/13.jpg" },
    ],
  },
  {
    slug: "soft-flooring",
    t: "რბილი იატაკები",
    d: "რბილი იატაკების მოწყობა, საფუძვლის მომზადება რბილი იატაკების დასაგებად.",
    img: "/img/services/soft-flooring.webp",
    gallery: [
      { src: "/img/products/soft-floors/02.jpg" },
      { src: "/img/products/soft-floors/03.jpg" },
      { src: "/img/products/soft-floors/04.jpg" },
      { src: "/img/products/soft-floors/05.webp" },
      { src: "/img/products/soft-floors/06.jpg" },
      { src: "/img/products/soft-floors/07.jpg" },
      { src: "/img/products/soft-floors/08.jpg" },
      { src: "/img/products/soft-floors/09.jpg" },
      { src: "/img/products/soft-floors/10.jpg" },
    ],
  },
  {
    slug: "insulation",
    t: "თბოიზოლაცია",
    d: "შენობების, მილსადენების და ტექნოლოგიური მოწყობილობების თბოიზოლაციის სამუშაოების შესრულება.",
    img: "/img/services/insulation.jpg",
    gallery: [
      { src: "/img/products/insulation-jackets/02.jpg" },
      { src: "/img/products/insulation-jackets/03.jpg" },
      { src: "/img/products/insulation-jackets/04.jpg" },
      { src: "/img/products/insulation-jackets/05.jpg" },
      { src: "/img/products/insulation-jackets/06.jpg" },
      { src: "/img/products/insulation-jackets/07.jpg" },
      { src: "/img/products/insulation-jackets/08.jpg" },
      { src: "/img/products/insulation-jackets/09.jpg" },
      { src: "/img/products/insulation-jackets/10.jpg" },
      { src: "/img/products/pir-spray-foam/01.jpg" },
      { src: "/img/products/pir-boards/01.jpg" },
      { src: "/img/products/prefabricated-pipes/01.webp" },
      { src: "/img/products/pir-spray-foam/02.jpg" },
      { src: "/img/products/pir-spray-foam/03.jpg" },
      { src: "/img/products/pir-spray-foam/04.jpg" },
      { src: "/img/products/pir-spray-foam/05.jpg" },
      { src: "/img/products/pir-boards/02.jpg" },
      { src: "/img/products/pir-spray-foam/06.jpg" },
      { src: "/img/products/pir-boards/03.jpg" },
      { src: "/img/products/pir-boards/04.jpg" },
      { src: "/img/products/prefabricated-pipes/02.png" },
      { src: "/img/products/prefabricated-pipes/03.png" },
      { src: "/img/services/insulation/23.jpg" },
      { src: "/img/products/prefabricated-pipes/04.jpg" },
      { src: "/img/products/prefabricated-pipes/05.png" },
    ],
  },
  {
    slug: "deck-flooring",
    t: "დეკის და აწეული იატაკები",
    d: "დეკის და ტექნოლოგიური აწეული იატაკების მოწყობა ქვეკონსტრუქციის მონტაჟით.",
    img: "/img/services/deck-flooring.jpg",
    gallery: [
      { src: "/img/products/deck-floors/02.jpg" },
      { src: "/img/products/deck-floors/03.jpg" },
      { src: "/img/products/deck-floors/04.jpg" },
      { src: "/img/products/deck-floors/05.webp" },
      { src: "/img/products/deck-floors/06.webp" },
      { src: "/img/products/deck-floors/07.jpg" },
      { src: "/img/products/deck-floors/08.png" },
      { src: "/img/products/deck-floors/09.jpg" },
      { src: "/img/products/deck-floors/11.jpg" },
      { src: "/img/products/deck-floors/12.jpg" },
      { src: "/img/products/deck-floors/13.jpg" },
      { src: "/img/products/deck-floors/14.jpg" },
      { src: "/img/products/deck-floors/15.jpg" },
      { src: "/img/products/deck-floors/16.jpg" },
      { src: "/img/products/deck-floors/17.jpg" },
      { src: "/img/products/deck-floors/18.jpg" },
      { src: "/img/products/deck-floors/19.jpg" },
      { src: "/img/products/deck-floors/20.jpg" },
      { src: "/img/products/deck-floors/21.jpg" },
      { src: "/img/products/deck-floors/23.jpg" },
      { src: "/img/products/deck-floors/26.jpg" },
      { src: "/img/products/deck-floors/27.jpg" },
      { src: "/img/products/deck-floors/01.jpg" },
      { src: "/img/products/deck-floors/29.jpg" },
      { src: "/img/products/deck-floors/30.jpg" },
      { src: "/img/products/deck-floors/31.jpg" },
      { src: "/img/products/deck-floors/32.png" },
      { src: "/img/products/deck-floors/33.jpg" },
    ],
  },
  {
    slug: "floor-preparation",
    t: "იატაკის საფუძვლის მომზადება",
    d: "იატაკის საფუძვლის მომზადება შემდგომი სამუშაოებისათვის: მოჭიმვის გაძლიერება, აღდგენა, ბეტონის და მოჭიმვის მოხეხვა სპეციალური მექანიზმებით, თვითსწორებადი მასის დასხმა და ა.შ.",
    img: "/img/services/floor-preparation.jpg",
    children: ["floor-screed", "screed-repair", "self-leveling"],
    intro: [
      { p: "იმისათვის, რომ თქვენი ახალი იატაკი ისეთი გამოვიდეს, როგორიც თქვენ გსურთ და წარმოგიდგენიათ, აუცილებელია მისთვის წინასწარ მომზადდეს საფუძველი. საფუძვლის მომზადება, კი იატაკის მოჭიმვით იწყება. სამწუხაროდ ხშირია შემთხვევები, როცა მოჭიმვის ხარისხს არ აქცევენ სათანადო ყურადღებას, თვლიან რომ ეს მარტივი საქმეა და ნებისმიერს შეუძლია მისი კარგად შესრულება. ასეთი მიდგომის შედეგად როგორც წესი ვღებულობთ უხარისხოდ შესრულებულ, არამდგრად ქვიშა-ცემენტის საფარს, რომელიც დაღარულია ღრმა და გრძელი ბზარებით, ხოლო ზედაპირი კი უსწორმასწოროა. ასეთი მოჭიმვა არ გამოგვადგება იატაკის საფუძვლად, რადგან მასზე დაგებული პარკეტი და/ან ნებისმიერი სხვა ტიპის იატაკიც ასეთივე უხარისხო, უსწორმასწორო და რაც მთავარია არამყარი ანუ შლადი და/ან ადვილად მტვრევადი გამოვა." },
      { h: "დაზიანებული მოჭიმვის აღდგენა და გამყარება შესაძლებელია", p: "მოკლედ, თუ თქვენ უკვე გააკეთეთ მოჭიმვა და მისი ხარისხი გაეჭვებთ, დაგვიკავშირდით და ჩვენი პროფესიონალი სპეციალისტები უზრუნველყოფენ სწორი გადაწყვეტილების მიღებას. ჩვენი კომპანია ფლობს დაზიანებული და ცუდად მოწყობილი მოჭიმვების გამოსწორების, შერემონტებისა და გაძლიერების საკმაო ცოდნასა და გამოცდილებას. სპეციალური სამშენებლო ქიმიის გამოყენებით ხშირ შემთხვევებში ვახერხებთ არსებული მოჭიმვის აყრისა და ახლიდან დასხმის თავიდან აცილებას, თანაც გარანტიით." },
      { h: "ჩვენ გთავაზობთ იატაკის შემდეგ სახეობებს", list: ["რბილი იატაკი რულონური ტიპის", "რბილი იატაკის ფილები", "ვინილის იატაკის საფარი რულონებში", "ვინილის იატაკის ფილები", "დეკის იატაკი", "იმიტირებული იატაკი", "ლამინირებული პარკეტი (ლამინატი)", "ნატურალური ხის იატაკი", "კერამიკული და კერამგრანიტის ფილები", "ინდუსტრიული იატაკები"] },
    ],
    gallery: [
      { src: "/img/services/floor-preparation/01.jpg" },
      { src: "/img/services/floor-preparation/02.jpg" },
      { src: "/img/services/floor-preparation/03.jpg" },
      { src: "/img/services/floor-preparation/04.jpg" },
      { src: "/img/services/floor-preparation/05.jpg" },
      { src: "/img/services/floor-preparation/06.jpg" },
    ],
  },
  {
    slug: "sandwich-panels",
    t: "სენდვიჩ პანელები",
    d: "სენდვიჩ პანელების, მზა ტიხრის პანელების, დეკორატიული პანელების მონტაჟი.",
    img: "/img/services/sandwich-panels.jpg",
    gallery: [
      { src: "/img/products/sandwich-panels/02.jpg", caption: "ქვაბამბის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/09.webp", caption: "კომბინირებული სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/08.jpg", caption: "პოლიურეთანის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/07.jpg", caption: "პოლიურეთანის სასახურავე სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/06.jpg", caption: "პოლიურეთანის სახურავის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/05.jpg", caption: "პოლიურეთანის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/04.webp", caption: "ქვაბამბის სახურავის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/03.jpg", caption: "ქვაბამბის სენდვიჩ-პანელი" },
      { src: "/img/products/sandwich-panels/01.jpg", caption: "ქვაბამბის სახურავის სენდვიჩ-პანელი" },
    ],
  },
  {
    slug: "decorative-panels",
    t: "დეკორატიული პანელები",
    d: "დეკორატიული პანელების მონტაჟი.",
    img: "/img/services/decorative-panels.jpg",
    intro: [
      { p: "ეს არის კედლის და ჭერის მოსაპირკეთებელი მზა პანელები – გარე და შიდა ფასადებისათვის. ისინი პოლიესტერის მასალით, მინაბოჭკოთი, ბუნებრივი ხისა და ქვის ფხვნილებითა და სპეციალური ქიმიური ნივთიერებების სინთეზით მზადდება. ეკოლოგიურად სუფთაა. ხელით შეხებისასაც ნამდვილი, ნატურალური მასალის შეგრძნებას იძლევა. ამ პანელების დამამზადებლები ევროპული კომპანიები არიან, ხოლო საქართველოში ჩვენ შემოგვაქვს და ვამონტაჟებთ." },
      { p: "ნუ დაკარგავთ დროს სხვა გადაწყვეტილებების ძებნაში, დაგვიკავშირდით და მიიღეთ ჩვენგან ნებისმიერი თქვენთვის სასურველი ზედაპირისა და ტექსტურის მქონე მზა პანელები ყოველ კონკრეტულ პროექტზე მორგებით, ადგილზე მიწოდებითა და უსწრაფესი მონტაჟით." },
    ],
    gallery: [
      { src: "/img/products/decorative-panels/01.jpg" },
      { src: "/img/products/decorative-panels/02.jpg" },
      { src: "/img/products/decorative-panels/03.jpg" },
      { src: "/img/products/decorative-panels/04.jpg" },
      { src: "/img/products/decorative-panels/05.jpg" },
      { src: "/img/products/decorative-panels/06.jpg" },
      { src: "/img/products/decorative-panels/07.jpg" },
      { src: "/img/products/decorative-panels/08.jpg" },
      { src: "/img/products/decorative-panels/09.jpg" },
      { src: "/img/products/decorative-panels/10.jpg" },
      { src: "/img/products/decorative-panels/11.jpg" },
      { src: "/img/products/decorative-panels/12.jpg" },
      { src: "/img/products/decorative-panels/13.jpg" },
      { src: "/img/products/decorative-panels/14.jpg" },
      { src: "/img/products/decorative-panels/15.jpg" },
      { src: "/img/products/decorative-panels/16.jpg" },
      { src: "/img/products/decorative-panels/17.jpg" },
      { src: "/img/products/decorative-panels/18.jpg" },
      { src: "/img/products/decorative-panels/19.jpg" },
      { src: "/img/products/decorative-panels/20.jpg" },
      { src: "/img/products/decorative-panels/21.jpg" },
      { src: "/img/products/decorative-panels/22.jpg" },
      { src: "/img/products/decorative-panels/23.jpg" },
      { src: "/img/products/decorative-panels/24.jpg" },
      { src: "/img/products/decorative-panels/25.jpg" },
      { src: "/img/products/decorative-panels/26.jpg" },
      { src: "/img/products/decorative-panels/27.jpg" },
      { src: "/img/products/decorative-panels/28.jpg" },
      { src: "/img/products/decorative-panels/29.jpg" },
      { src: "/img/products/decorative-panels/30.jpg" },
      { src: "/img/products/decorative-panels/31.jpg" },
      { src: "/img/products/decorative-panels/32.jpg" },
      { src: "/img/products/decorative-panels/33.jpg" },
      { src: "/img/products/decorative-panels/34.jpg" },
      { src: "/img/products/decorative-panels/35.jpg" },
      { src: "/img/products/decorative-panels/36.jpg" },
      { src: "/img/products/decorative-panels/37.jpg" },
      { src: "/img/products/decorative-panels/38.jpg" },
      { src: "/img/products/decorative-panels/39.jpg" },
      { src: "/img/products/decorative-panels/40.jpg" },
      { src: "/img/products/decorative-panels/41.jpg" },
      { src: "/img/products/decorative-panels/42.jpg" },
      { src: "/img/products/decorative-panels/43.jpg" },
      { src: "/img/products/decorative-panels/44.jpg" },
      { src: "/img/products/decorative-panels/45.jpg" },
      { src: "/img/products/decorative-panels/46.jpg" },
      { src: "/img/products/decorative-panels/47.jpg" },
      { src: "/img/products/decorative-panels/48.jpg" },
      { src: "/img/products/decorative-panels/49.jpg" },
      { src: "/img/products/decorative-panels/50.jpg" },
    ],
  },
  {
    slug: "hvac",
    t: "HVAC — გათბობა, ვენტილაცია, ჰაერის კონდიცირება",
    d: "HVAC (გათბობა, ვენტილაცია, ჰაერის კონდიცირება) სისტემების პროექტირება და მონტაჟი.",
    img: "/img/services/hvac.jpg",
    intro: [
      { p: "გათბობა, ვენტილაცია და ჰაერის კონდიცირება კომფორტის ის კომპონენტებია, რომლებსაც არ გააჩნიათ ხარისხის, მრავალფეროვნებისა და ღირებულების ზღვარი. შესაძლებელია ყველა ეს კომპონენტი წარმოდგენილი იყოს როგორც ცალკე სისტემა ან მოწყობილობა, ასევე ერთმანეთში ინტეგრირებული მაღალეფექტური, ცენტრალიზებული და ავტომატურად მართვადი სისტემა, რომელსაც კომპიუტერული პროგრამა ადამიანის ჩარევის გარეშე ამუშავებს." },
      { h: "დაზოგე ენერგია და ფული", p: "მიმდინარე ეკოლოგიური და ენერგეტიკული გამოწვევები გვაიძულებენ სულ უფრო მეტად დავხვეწოთ და განვავითაროთ სითბური ენერგიის უკუგების მეთოდები და მოწყობილობები. დედამიწაზე ენერგო რესურსების შემცირების ტენდენცია ენერგომატარებლებზე ფასების მუდმივ მატებას იწვევს. რეკუპერაციის გარეშე ფაქტიურად წარმოუდგენელი გახდა საშუალო და მსხვილი სიდიდის ობიექტების სითბოთი და სიცივით უზრუნველყოფა." },
      { h: "ყურადღება მიაქციე ჰაერს, რომელსაც სუნთქავ", p: "ჰაერის მხოლოდ გაცივება და გათბობა აღარ არის საკმარისი სრული კომფორტისა და ჯანმრთელი გარემოს შექმნისათვის. დღესდღეობით სულ უფრო ხშირად გვიწევს ჰაერის დამუშავებაზე ზრუნვა, რათა მისი ხარისხი საჭირო პარამეტრებს შევუსაბამოთ. ჰაერის დამუშავება ტემპერატურის რეგულირების გარდა მისი სისუფთავის, ტენიანობის და ნაკადების მართვასაც გულისხმობს." },
      { h: "გვენდე ჩვენ — შეიქმენი ჯანსაღი და კომფორტული გარემო", p: "საკმაოდ რთულია ინფორმაციულად უკიდურესად გადატვირთულ ეპოქაში ჯანსაღი და კომფორტული გარემოს შექმნისათვის საჭირო ყველა ელემენტის შესწავლა და მათგან ოპტიმალურის შერჩევა. ჩვენი საერთაშორისო გუნდი, რომელსაც აღნიშნულ სექტორში მუშაობის 30 წლიანი გამოცდილება აქვს, სიამოვნებით გაგიწევთ პროფესიონალურ კონსულტაციებს, მოგცემთ რეკომენდაციებს და შეიმუშავებს ოპტიმალურ კონცეფციას თქვენი საჭიროებისა და/ან ტექნიკური დავალების შესაბამისად." },
    ],
    gallery: [
      { src: "/img/products/hvac/02.jpg" },
      { src: "/img/products/hvac/03.jpg" },
      { src: "/img/products/hvac/04.jpg" },
      { src: "/img/products/hvac/05.jpg" },
      { src: "/img/products/hvac/06.jpg" },
      { src: "/img/products/hvac/07.jpg" },
      { src: "/img/products/ahu/01.jpg" },
      { src: "/img/products/ahu/02.jpg" },
      { src: "/img/products/recuperators/01.jpg" },
      { src: "/img/products/textile-ducts/01.png" },
      { src: "/img/products/recuperators/02.webp" },
      { src: "/img/products/recuperators/03.png" },
      { src: "/img/products/recuperators/04.png" },
      { src: "/img/products/recuperators/05.png" },
      { src: "/img/services/hvac/21.jpg" },
      { src: "/img/products/recuperators/06.jpg" },
      { src: "/img/products/recuperators/07.jpg" },
      { src: "/img/products/textile-ducts/02.jpg" },
      { src: "/img/products/textile-ducts/03.png" },
      { src: "/img/products/textile-ducts/04.jpg" },
      { src: "/img/products/textile-ducts/05.png" },
      { src: "/img/products/textile-ducts/06.jpg" },
      { src: "/img/products/textile-ducts/07.png" },
      { src: "/img/products/textile-ducts/08.png" },
      { src: "/img/products/textile-ducts/09.png" },
      { src: "/img/products/textile-ducts/10.jpg" },
      { src: "/img/products/textile-ducts/11.jpg" },
      { src: "/img/products/textile-ducts/12.jpg" },
      { src: "/img/products/textile-ducts/13.jpg" },
      { src: "/img/products/textile-ducts/14.jpg" },
    ],
  },
  {
    slug: "air-filters",
    t: "ჰაერის ფილტრები — შერჩევა, მონტაჟი და შეცვლა",
    d: "ჰაერის ფილტრების შერჩევა, მოწოდება, მონტაჟი და პერიოდული შეცვლა სავენტილაციო და HVAC სისტემებში — G4, F7/F9, HEPA (H13/H14) და ULPA კლასები კლინიკების, საავადმყოფოების, ლაბორატორიების, ფარმაცევტული და კვების ობიექტებისთვის.",
    img: "/img/services/air-filters.jpg",
    gallery: [
      { src: "/img/products/air-filters/04.jpg" },
      { src: "/img/products/air-filters/05.jpg" },
      { src: "/img/products/air-filters/01.png" },
      { src: "/img/products/air-filters/02.jpg" },
      { src: "/img/products/air-filters/03.jpg" },
      { src: "/img/products/air-filters/06.jpg" },
    ],
  },
  {
    slug: "textile-ducts",
    t: "ტექსტილის ჰაერსადენები",
    d: "ტექსტილის ჰაერსადენების მოწოდება და მონტაჟი.",
    img: "/img/services/textile-ducts.jpg",
    gallery: [
      { src: "/img/products/textile-ducts/01.png" },
      { src: "/img/products/textile-ducts/02.jpg" },
      { src: "/img/products/textile-ducts/03.png" },
      { src: "/img/products/textile-ducts/04.jpg" },
      { src: "/img/products/textile-ducts/05.png" },
      { src: "/img/products/textile-ducts/06.jpg" },
      { src: "/img/products/textile-ducts/07.png" },
      { src: "/img/products/textile-ducts/08.png" },
      { src: "/img/products/textile-ducts/09.png" },
      { src: "/img/products/textile-ducts/10.jpg" },
      { src: "/img/products/textile-ducts/11.jpg" },
      { src: "/img/products/textile-ducts/12.jpg" },
      { src: "/img/products/textile-ducts/13.jpg" },
      { src: "/img/products/textile-ducts/14.jpg" },
      { src: "/img/services/textile-ducts/15.jpg" },
      { src: "/img/services/textile-ducts/16.jpg" },
      { src: "/img/services/textile-ducts/17.jpg" },
      { src: "/img/services/textile-ducts/18.jpg" },
      { src: "/img/services/textile-ducts/19.jpg" },
      { src: "/img/services/textile-ducts/20.jpg" },
      { src: "/img/services/textile-ducts/21.jpg" },
      { src: "/img/services/textile-ducts/22.jpg" },
      { src: "/img/services/textile-ducts/23.jpg" },
      { src: "/img/services/textile-ducts/24.jpg" },
      { src: "/img/services/textile-ducts/25.jpg" },
      { src: "/img/services/textile-ducts/26.jpg" },
      { src: "/img/services/textile-ducts/27.jpg" },
      { src: "/img/services/textile-ducts/28.jpg" },
      { src: "/img/services/textile-ducts/29.jpg" },
      { src: "/img/services/textile-ducts/30.jpg" },
      { src: "/img/services/textile-ducts/31.jpg" },
      { src: "/img/services/textile-ducts/32.jpg" },
    ],
  },
  {
    slug: "refrigeration",
    t: "სამაცივრე სისტემები",
    d: "მაცივარ აგრეგატების, სამაცივრე სისტემების პროექტირება, მოწოდება და მონტაჟი.",
    img: "/img/services/refrigeration.jpg",
    fit: "contain",
    gallery: [
      { src: "/img/products/cold-storage-systems/02.jpg", caption: "დამტვირთველ-დამცლელი კამერები" },
      { src: "/img/products/cold-storage-systems/03.png", caption: "ინდუსტრიული კარი" },
      { src: "/img/products/cold-storage-systems/04.jpg", caption: "სტანდარტული როლეტის ტიპის სწრაფი კარი" },
      { src: "/img/products/loading-ramps/01.jpg", caption: "პნევმატური და ჰიდრავლიკური პანდუსის სისტემები" },
      { src: "/img/products/loading-ramps/02.jpg", caption: "გასაბერი კარის ღიობის შემამჭიდროვებელი სისტემა" },
      { src: "/img/products/loading-ramps/03.jpg", caption: "კარის ღიობის შემამჭიდროვებელი ბალიშის სისტემა" },
      { src: "/img/products/loading-ramps/04.jpg", caption: "პანდუსის ავტომატური სისტემები" },
      { src: "/img/products/loading-ramps/05.png", caption: "ჰიდრავლიკური რამპის სისტემები" },
      { src: "/img/products/cold-storage-doors/01.png", caption: "ბარის ტიპის კარი, 2-ფრთიანი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/02.png", caption: "ბარის ტიპის კარი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/03.jpg", caption: "თბოიზოლირებული როლეტის ტიპის სწრაფი კარი" },
      { src: "/img/products/cold-storage-doors/04.png", caption: "კარი 1-ფრთიანი, ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/05.jpg", caption: "კარი 2-ფრთიანი, ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/06.png", caption: "სერვის კარი, ნახევრად იზოლირებული" },
      { src: "/img/products/cold-storage-doors/07.png", caption: "სერვის კარი" },
      { src: "/img/products/cold-storage-doors/08.png", caption: "სრიალა კარი, ავტომატური, ჰორიზონტალური" },
      { src: "/img/products/cold-storage-doors/09.png", caption: "სრიალა კარი, ვერტიკალური" },
      { src: "/img/products/cold-storage-doors/10.jpg", caption: "სრიალა კარი, ჰერმეტული, წნევის კონტროლით" },
      { src: "/img/products/cold-storage-doors/11.png", caption: "სრიალა კარი, ჰორიზონტალური" },
      { src: "/img/products/cold-storage-doors/12.png", caption: "სრიალა კარი ანჯამებზე" },
      { src: "/img/products/cold-storage-doors/13.png", caption: "სრიალა კარი მონორელსზე" },
    ],
  },
  {
    slug: "steam-units",
    t: "ინდუსტრიული ორთქლის წარმოებისა და მართვის სისტემები",
    d: "ინდუსტრიული ორთქლის სისტემების სრული მომსახურება: კონცეფციის შემუშავება, პროექტირება, მოწოდება, მონტაჟი და შემდგომი სერვისი დიაგნოსტიკის ჩათვლით.",
    img: "/img/services/steam-units.jpg",
    gallery: [],
  },
  {
    slug: "suspended-ceilings",
    t: "შეკიდული ჭერების მოწოდება, მონტაჟი",
    d: "შეკიდული ჭერების მონტაჟი: Clip inn; Lay inn; Grilatto, ასევე ინდუსტრიული, თაბაშირ-მუყაოს და სხვადასხვა ტიპის პანელოვანი ჭერები.",
    img: "/img/services/suspended-ceilings.jpg",
    intro: [
      { h: "ჭერიც არის და ჭერიც", p: "ამოუწურავია ჭერის თემა თავისი მრავალფეროვნების გამო, მითუმეტეს, რომ დღევანდელ დღეს ჭერს უბრალო გადახურვისა და დეკორის ფუნქციის გარდა მრავალი სხვა, არანაკლებ მნიშვნელოვანი ფუნქცია შეემატა. თანამედროვე შენობებში ინტერიერის ეს მნიშვნელოვანი ელემენტი მთელ რიგ ტექნოლოგიებს მოიცავს, როგორებიც არის: თბო და ბგერითი იზოლაცია, ენერგიის დაზოგვა, ხმაურის ჩახშობა, განათების ეფექტის გაზრდა, ჰიგიენა და ბოლოს და ბოლოს შეკიდულ ჭერს მიღმა შეგვიძლია დავმალოთ ყველა და ნებისმიერი საინჟინრო კომუნიკაცია. ფუნქციონალური დატვირთვისა და შესახედაობის მიხედვით შესაძლებელია შეირჩეს სხვადასხვა ტიპისა და მასალის ჭერი." },
      { h: "ჭერის შესყიდვამდე დაგვიკავშირდით", p: "იმისათვის, რომ თქვენი ახალი ჭერი ზუსტად აკმაყოფილებდეს როგორც თქვენს გემოვნებას, ასევე თქვენს ტექნიკურ მოთხოვნებს – დაგვიკავშირდით და ჩვენი გუნდის პროფესიონალი სპეციალისტი დაგეხმარებათ ოპტიმალური გადაწყვეტილების მიღებაში. ჭერის ტიპის, კონსტრუქციისა და მასალის შერჩევა პირველ რიგში შენობის დანიშნულებიდან და ფუნქციიდან გამომდინარე ხდება. ჭერის ტიპიდან გამომდინარე ხდება მისი კონსტრუქციის განსაზღვრა, გაანგარიშება და მთლიანობაში ჭერის მოსაწყობად საჭირო მასალების დათვლა." },
      { p: "გთავაზობთ ხის, მეტალის, ვინილის, კომპოზიტური, თუ იმიტირებული მასალისაგან დამზადებული ჭერების ფართო ასორტიმენტს თქვენი ობიექტის დანიშნულებისა და ფუნქციის შესაბამისად. მასალებისა და სამუშაოს შეკვეთის შემთხვევაში რეკომენდაციები, კონსულტაცია და დაანგარიშება უფასოა." },
    ],
    gallery: [
      { src: "/img/products/suspended-ceilings/01.jpg" },
      { src: "/img/services/suspended-ceilings/02.jpg" },
      { src: "/img/products/suspended-ceilings/02.jpg" },
      { src: "/img/services/suspended-ceilings/04.jpg" },
      { src: "/img/products/suspended-ceilings/30.jpg" },
      { src: "/img/services/suspended-ceilings/06.jpg" },
      { src: "/img/products/suspended-ceilings/33.jpg" },
      { src: "/img/services/suspended-ceilings/08.jpg" },
      { src: "/img/services/suspended-ceilings/09.jpg" },
      { src: "/img/services/suspended-ceilings/10.jpg" },
      { src: "/img/services/suspended-ceilings/11.webp" },
      { src: "/img/services/suspended-ceilings/12.png" },
      { src: "/img/products/suspended-ceilings/04.jpg" },
      { src: "/img/products/suspended-ceilings/05.jpg" },
      { src: "/img/products/suspended-ceilings/06.jpg" },
      { src: "/img/products/suspended-ceilings/07.jpg" },
      { src: "/img/products/suspended-ceilings/08.webp" },
      { src: "/img/products/suspended-ceilings/09.webp" },
      { src: "/img/products/suspended-ceilings/10.webp" },
      { src: "/img/products/suspended-ceilings/11.jpg" },
      { src: "/img/products/suspended-ceilings/12.webp" },
      { src: "/img/products/suspended-ceilings/13.webp" },
      { src: "/img/products/suspended-ceilings/14.webp" },
      { src: "/img/products/suspended-ceilings/15.webp" },
      { src: "/img/products/suspended-ceilings/16.webp" },
      { src: "/img/products/suspended-ceilings/17.webp" },
      { src: "/img/products/suspended-ceilings/18.jpg" },
      { src: "/img/products/suspended-ceilings/19.webp" },
      { src: "/img/products/suspended-ceilings/20.webp" },
      { src: "/img/products/suspended-ceilings/21.webp" },
      { src: "/img/products/suspended-ceilings/22.webp" },
      { src: "/img/products/suspended-ceilings/23.webp" },
      { src: "/img/products/suspended-ceilings/24.webp" },
      { src: "/img/products/suspended-ceilings/25.webp" },
      { src: "/img/products/suspended-ceilings/26.jpg" },
      { src: "/img/products/suspended-ceilings/27.jpg" },
      { src: "/img/products/suspended-ceilings/28.jpg" },
      { src: "/img/products/suspended-ceilings/29.jpg" },
      { src: "/img/products/suspended-ceilings/31.jpg" },
      { src: "/img/products/suspended-ceilings/32.jpg" },
      { src: "/img/products/suspended-ceilings/34.jpg" },
      { src: "/img/products/suspended-ceilings/35.jpg" },
      { src: "/img/products/suspended-ceilings/36.jpg" },
      { src: "/img/products/suspended-ceilings/37.png" },
      { src: "/img/products/suspended-ceilings/38.png" },
      { src: "/img/products/suspended-ceilings/39.webp" },
      { src: "/img/products/suspended-ceilings/40.jpg" },
      { src: "/img/products/suspended-ceilings/41.jpg" },
      { src: "/img/products/suspended-ceilings/42.jpg" },
      { src: "/img/products/suspended-ceilings/43.jpg" },
      { src: "/img/products/suspended-ceilings/44.jpg" },
      { src: "/img/products/suspended-ceilings/45.jpg" },
      { src: "/img/products/suspended-ceilings/46.jpg" },
      { src: "/img/products/suspended-ceilings/47.jpg" },
      { src: "/img/products/suspended-ceilings/48.jpg" },
      { src: "/img/products/suspended-ceilings/49.jpg" },
    ],
  },
  {
    slug: "laminate",
    t: "ლამინირებული იატაკის მონტაჟი",
    d: "ლამინირებული იატაკების მონტაჟი.",
    img: "/img/services/laminate.jpg",
    gallery: [],
  },
  {
    slug: "industrial-floors",
    t: "ინდუსტრიული ტიპის იატაკების მოწყობა",
    d: "ინდუსტრიული ტიპის იატაკების მოწყობა.",
    img: "/img/services/industrial-floors.jpg",
    gallery: [
      { src: "/img/services/industrial-floors/01.jpg" },
      { src: "/img/services/industrial-floors/02.jpg" },
      { src: "/img/services/industrial-floors/03.jpg" },
    ],
  },
  {
    slug: "ceramic-tiles",
    t: "კერამიკული ფილების დაგება",
    d: "კერამიკული ფილების დაგება და კედელზე გაკვრა.",
    img: "/img/services/ceramic-tiles.jpg",
    gallery: [],
  },
  {
    slug: "painting",
    t: "სამღებრო სამუშაოები",
    d: "ინტერიერის და ფასადის სამღებრო სამუშაოების შესრულება.",
    img: "/img/services/painting.jpg",
    gallery: [],
  },
  {
    slug: "electrical",
    t: "ავტომატიზაცია",
    d: "HVAC-ის, წყალმომარაგების, ფილტრაციის და ორთქლის სისტემების სრულად ავტომატიზებული მართვა — BMS / SCADA.",
    img: "/img/services/electrical.jpg",
    gallery: [],
  },
  {
    slug: "design-renovation",
    t: "პროექტირება / რემონტი",
    d: "პროექტირება და რემონტი: საყოფაცხოვრებო, კომერციული, ჯანდაცვითი, ინდუსტრიული ობიექტები.",
    img: "/img/services/design-renovation.jpg",
    gallery: [],
  },
  {
    slug: "medical-planning",
    t: "სამედიცინო ობიექტების ტექნოლოგიური დაგეგმარება",
    d: "სამედიცინო ობიექტების ტექნოლოგიური დაგეგმარება, კონცეფციის შემუშავება, პროექტირება, შესრულება.",
    img: "/img/services/medical-planning.jpg",
    gallery: [],
  },
  {
    slug: "water-treatment",
    t: "წყლის გამწმენდი სისტემები",
    d: "წყლის ფილტრაციის, დარბილების და წმენდის სისტემების შერჩევა, მოწოდება, მონტაჟი და სერვისი.",
    img: "/img/products/water-treatment/cover.png",
    gallery: [],
  },
  {
    slug: "x-ray-protection",
    t: "რენტგენოდაცვა",
    d: "სამედიცინო ობიექტებში რენტგენოდამცავი სისტემების — ტყვიის ფურცლების, თეჯირების, კარების — მოწოდება და მონტაჟი.",
    img: "/img/gallery/IMG_6200.jpg",
    gallery: [
      { src: "/img/gallery/IMG_5658.jpg" },
      { src: "/img/gallery/IMG_6200.jpg" },
      { src: "/img/gallery/IMG_7609.jpg" },
      { src: "/img/gallery/IMG_8388.jpg" },
      { src: "/img/gallery/IMG_8391.jpg" },
    ],
  },
  {
    slug: "water-sewage",
    t: "წყალმომარაგება — კანალიზაცია",
    d: "წყალმომარაგება: ცივი და ცხელი წყლით უზრუნველყოფა, წყლის გამწმენდი სისტემების მონტაჟი, სადრენაჟო და საკანალიზაციო ქსელებისა და სისტემების მონტაჟი.",
    img: "/img/services/water-sewage.jpg",
    gallery: [],
  },
];

export const subServices: Item[] = [
  {
    slug: "floor-screed",
    t: "იატაკის მოჭიმვა ქვიშა-ცემენტის ხსნარით",
    d: "იატაკის მოჭიმვა ქვიშა-ცემენტის ხსნარით.",
    img: "/img/services/floor-preparation/03.jpg",
    parent: "floor-preparation",
    gallery: [
      { src: "/img/services/floor-preparation/03.jpg" },
    ],
  },
  {
    slug: "screed-repair",
    t: "დაზიანებული მოჭიმვის აღდგენა-გამყარება",
    d: "დაზიანებული მოჭიმვის აღდგენა-გამყარება.",
    img: "/img/services/screed-repair/01.jpg",
    parent: "floor-preparation",
    gallery: [
      { src: "/img/services/screed-repair/01.jpg" },
      { src: "/img/services/screed-repair/02.jpg" },
      { src: "/img/services/screed-repair/03.jpg" },
      { src: "/img/services/screed-repair/04.webp" },
      { src: "/img/services/floor-preparation/06.jpg" },
      { src: "/img/services/screed-repair/06.jpg" },
      { src: "/img/services/floor-preparation/05.jpg" },
      { src: "/img/services/floor-preparation/04.jpg" },
    ],
  },
  {
    slug: "self-leveling",
    t: "თვითსწორებადი მასის დასხმა",
    d: "თვითსწორებადი მასის დასხმა.",
    img: "/img/services/self-leveling/01.jpg",
    parent: "floor-preparation",
    gallery: [
      { src: "/img/services/self-leveling/01.jpg" },
      { src: "/img/services/floor-preparation/01.jpg" },
      { src: "/img/services/floor-preparation/02.jpg" },
      { src: "/img/services/self-leveling/04.jpg" },
      { src: "/img/services/self-leveling/05.jpg" },
    ],
  },
];

export const serviceCatalog = makeCatalog({
  base: "/services",
  label: "სერვისები",
  noun: "სერვისი",
  features: { label: "სერვისი მოიცავს", items: ["კონსულტაციებს", "რეკომენდაციებს"] },
  copy: {
    others: "სხვა სერვისები",
    all: "ყველა სერვისი",
    order: "შეფასება და ვადები",
    cta: "გჭირდებათ სამუშაოების შეფასება?",
    missing: "ვერ იპოვეთ საჭირო სერვისი?",
  },
  top: services,
  sub: subServices,
});
