/**
 * Long-form product articles from the client's Word documents (2026-09),
 * one JSON file per product slug with Georgian and English text.
 * Regenerated by the merge script; edit the JSON files to change copy.
 */
import type { ContentBlock, ItemText } from "../catalog";
import type { Lang } from "../i18n";
import airFilters from "./air-filters.json";
import automation from "./automation.json";
import chillerUnits from "./chiller-units.json";
import deckFloors from "./deck-floors.json";
import insulationJackets from "./insulation-jackets.json";
import pirBoards from "./pir-boards.json";
import pirSprayFoam from "./pir-spray-foam.json";
import prefabricatedPipes from "./prefabricated-pipes.json";
import recuperators from "./recuperators.json";
import sandwichPanels from "./sandwich-panels.json";
import softFloors from "./soft-floors.json";
import steamUnits from "./steam-units.json";
import textileDucts from "./textile-ducts.json";
import vinylFloors from "./vinyl-floors.json";
import waterTreatment from "./water-treatment.json";

/** English is optional: without it the English page keeps its short catalogue text. */
type Article = { ka: ArticleText; en?: ArticleText };
type ArticleText = { t: string; d: string; content: ContentBlock[] };

const articles = {
  "air-filters": airFilters,
  "automation": automation,
  "chiller-units": chillerUnits,
  "deck-floors": deckFloors,
  "insulation-jackets": insulationJackets,
  "pir-boards": pirBoards,
  "pir-spray-foam": pirSprayFoam,
  "prefabricated-pipes": prefabricatedPipes,
  "recuperators": recuperators,
  "sandwich-panels": sandwichPanels,
  "soft-floors": softFloors,
  "steam-units": steamUnits,
  "textile-ducts": textileDucts,
  "vinyl-floors": vinylFloors,
  "water-treatment": waterTreatment,
} as unknown as Record<string, Article>;

/** Per language: slug → title, description and article, ready to lay over the catalogue. */
export const productArticles = Object.fromEntries(
  (["ka", "en"] as const).map((lang) => [
    lang,
    Object.fromEntries(Object.entries(articles).flatMap(([slug, a]) => (a[lang] ? [[slug, a[lang]]] : []))),
  ])
) as Record<Lang, Record<string, Partial<ItemText>>>;
